### PR TITLE
Fixes problem with get_interfaces_counters

### PR DESCRIPTION
**Pull request by tehhobbit**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

This PR is related to #75

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Just checked and this does not seem to break any backwards compatibility and indeed makes sense to restructure it like that.
But refactoring and changing the executed command implies different mock data for the tests:
- new command output under `napalm_eos/test/unit/mocked_data/test_get_interfaces_counters/normal/show_interfaces.json`
- new expected command output under `napalm_eos/test/unit/mocked_data/test_get_interfaces_counters/normal/expected_result.json`

Let me know if you have any questions.

**Comment by tehhobbit** [comment]
Sadly enough I dont have time to sort the mock data today, I will hopefully sort that tomorrow.

**Comment by tehhobbit** [comment]
Looking at coveralls this seems to be an issue with how lines are formatted rather that actually missing tests, but let me know if there is something you want changed.

**Comment by dbarrosop** [comment]
Don't worry about coveralls, your code is smaller than the previous one so untested code has more weight. Not your PR's fault. Looks good to me so I am merging it.

**Pull request merged**
