### PR TITLE
get_snmp without acl

### PR DESCRIPTION
**Pull request by ogenstad**

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Hi @ogenstad is this a fix for https://github.com/napalm-automation/napalm-eos/issues/113?

**Comment by ogenstad** [comment]
@mirceaulinic, yeah it was just to show a different solution.

**Comment by bewing** [comment]
Why is the regexp trying to match group?  EOS documentation states that group shouldn't show up in that command.

https://www.arista.com/en/um-eos-4172f/eos-section-38-4-snmp-commands#ww1154277

**Comment by ogenstad** [comment]
Have no idea about group, I didn't touch that part.

**Comment by dbarrosop** [comment]
I have no idea who wrote that and because of the split of the repos seems that some bits of ownership has been lost :(

@mirceaulinic was that you?

**Comment by mirceaulinic** [comment]
Yes, I have probably missed that. However, I didn't notice anything bad so far.

**Comment by dbarrosop** [comment]
No worries, just dead code. Can we just remove it then?

**Comment by mirceaulinic** [comment]
Yes, I think @bewing's proposal in https://github.com/napalm-automation/napalm-eos/pull/114 will not use that textfsm anymore.

**Comment by dbarrosop** [comment]
Right... should we close this PR then?

**Comment by mirceaulinic** [comment]
Anyway that `group` part is ignored when the regex is evaluated.

I let you decide which is more maintainable on the long term, I am perfectly fine with both approaches. I know you don't like TextFSM so I think we can close this one indeed.

**Comment by mirceaulinic** [comment]
I am going to close this one, in the favour of https://github.com/napalm-automation/napalm-eos/pull/114.

Thanks @ogenstad!

**Pull request closed without merging**
