### PR TITLE
Fix #53

### LINKED ISSUE #53: KeyError when executing get_bgp_neighbors_detail
### Description of Issue/Question

When the BGP session is down, the key representing the IP address of the neighbor is not set in the `bgp_summary` dictionary, which is the result of retrieving `show ipv6 bgp summary vrf all` and `show ip bgp summary vrf all` commands.
### napalm-eos version

0.3.0
### Network OS version

any
### Steps to Reproduce the Issue

Execute `get_bgp_neighbors_detail`
### Error Traceback

(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/state/home/mircea/napalm-eos/napalm_eos/eos.py", line 1302, in get_bgp_neighbors_detail
    [peer_info['remote_address']]['prefixAccepted'])
KeyError: u'1.2.3.4'
```

### PR DESCRIPTION
**Pull request by mirceaulinic**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by dbarrosop** [comment]
Could you also provide a test case or extend the current one with a BGP session down to make sure we test this?

**Comment by mirceaulinic** [comment]
Sure, that would be quite good actually.

Except from defining a new dir under https://github.com/napalm-automation/napalm-eos/tree/develop/test/unit/mocked_data/test_get_bgp_neighbors_detail, is there anything else I need to update to consider the test case?

**Comment by dbarrosop** [comment]
Yeah, that's everything needed. Create the folder and add the mocked data inside. The framework will pick it up.

**Comment by mirceaulinic** [comment]
Nice! Think I'm gonna love this new test framework!

**Pull request merged**
