### PR TITLE
use textfsm_extractor() from napalm_base

### PR DESCRIPTION
**Pull request by mirceaulinic**
Migrated to napalm_base.helpers & rearranged a bit the imports.

Depends on: https://github.com/napalm-automation/napalm-base/pull/8

### CODE REVIEW

**Comment by mirceaulinic** [comment]
This is an issue I expected and I think @fooelisa warned about that a couple of days ago: whenever we make a change in napalm_base we will need to wait till merged.
But I think we can survive with that.

Right now napalm_base.helpers cannot be imported.

**Comment by dbarrosop** [comment]
Don't we have to update the requirements to include jinja2 and gtextfsm?

**Comment by mirceaulinic** [comment]
They are already required by napalm_base, so should be enough.

**Comment by dbarrosop** [comment]
Yes, but I would rather have no requirements in napalm_base unless they are by all or most of the drivers. I guess jinja2 is used by all or most of the drivers but I am not sure about gtextfsm. Maybe we can leave it, should be a small dependency and it's rather small.

**Comment by dbarrosop** [comment]
Depends on: https://github.com/napalm-automation/napalm-base/pull/8

**Pull request merged**
