### PR TITLE
Group neighbors without peer-group under the '_' key

### PR DESCRIPTION
**Pull request by mirceaulinic**
Painful stuff here.
@itdependsnetworks owes me a beer for that :D

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Solves https://github.com/napalm-automation/napalm-eos/issues/119

**Comment by itdependsnetworks** [comment]
Lol, thanks! I was going to try and knock this out this weekend, but much appreciated!

**Comment by mirceaulinic** [comment]
There's something broken right now, I'll add also some test cases tomorrow.

Meanwhile would you mind testing this branch @itdependsnetworks? Curious if the structural changes are fine.

**Comment by mirceaulinic** [comment]
This method apparently had few other bugs:

```
E               AssertionError: Expected result varies on some keys {"IPv6-PEERS-GROUP-NAME": {"local_as": {"result": 13335, "expected": 0}, "neighbors": {"2001:db8::0:2": {"local_as": {"result": 13335, "expected": 0}}, "2001:db8::0:1": {"local_as": {"result": 13335, "expected": 0}}}}, "IPv4-PEERS-GROUP-NAME": {"local_as": {"result": 13335, "expected": 0}, "neighbors": {"192.168.0.1": {"local_as": {"result": 13335, "expected": 0}}, "172.17.17.1": {"local_as": {"result": 13335, "expected": 0}}}}}
```

The `local_as` key was wrong.

**Comment by dbarrosop** [comment]
+1

**Comment by itdependsnetworks** [comment]
looks good to me.

prior ```
>>> from napalm import get_network_driver
>>>
>>> eos_device='192.168.56.10'
>>> eos_user='ntc'
>>> eos_password='ntc123'
>>> driver = get_network_driver('eos')
>>> device = driver(eos_device, eos_user, eos_password)
>>> device.open()
>>> device.get_facts()
{u'os_version': u'4.15.5M-3054042.4155M', u'uptime': 252, u'interface_list': [u'Ethernet1', u'Management1'], u'vendor': u'Arista', u'serial_number': u'', u'model': u'vEOS', u'hostname': u'eos-leaf1', u'fqdn': u'eos-leaf1'}
>>> device.get_bgp_config()
{}
>>>
```

after
```
>>> from napalm import get_network_driver
>>>
>>> eos_device='192.168.56.10'
>>> eos_user='ntc'
>>> eos_password='ntc123'
>>> driver = get_network_driver('eos')
>>> device = driver(eos_device, eos_user, eos_password)
>>> device.open()
>>> device.get_facts()
{u'os_version': u'4.15.5M-3054042.4155M', u'uptime': 409, u'interface_list': [u'Ethernet1', u'Management1'], u'vendor': u'Arista', u'serial_number': u'', u'model': u'vEOS', u'hostname': u'eos-leaf1', u'fqdn': u'eos-leaf1'}
>>> device.get_bgp_config()
{u'_': {u'neighbors': {u'10.10.10.20': {u'export_policy': u'', u'remote_as': 104, u'import_policy': u'', u'prefix_limit': {}, u'local_as': 103, u'nhs': False, u'route_reflector_client': False, u'local_address': u'', u'authentication_key': u'', u'description': u'Verizon'}}, u'export_policy': u'', u'remote_as': 0, u'import_policy': u'', u'prefix_limit': {}, u'local_as': 103, u'multihop_ttl': 0, u'apply_groups': [], u'local_address': u'', u'remove_private_as': False, u'multipath': False, u'type': u'', u'description': u''}}
>>>
>>>
```

+1

**Review by dbarrosop — APPROVED** [review]

**Pull request merged**
