### PR TITLE
Remove comma

### PR DESCRIPTION
**Pull request by itdependsnetworks**
Was unsure how some of this was working, (e.g. $Interfaces vs ${Interfaces} ) and see that the comma was left in. This PR is not ready to go in, just wanted to see if it made sense before adjusting the getter

Also @bewing are you ok to add this to ntc-templates? 

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by mirceaulinic** [comment]
"First-time contributor" - after so much time. Wooo! :)

**Comment by itdependsnetworks** [comment]
lol, I know I owe the primary/secondary key, I think it got done this week

**Comment by bewing** [comment]
I remember there being an issue when I was originally developing regarding $Interfaces vs ${Interfaces} involving the list keyword in textfsm, but hey, tests pass, so I guess that bug was fixed somewhere.

What comma was missed?  Do we want to update the test case so that it fails without this patch?

**Comment by itdependsnetworks** [comment]
Current
```
FSM Table:
['Name', 'Route_Distinguisher', 'Interfaces']
['MGMT', '0:0', ['Vlan2, Vlan3, Vlan4']]
['NON', '<not set>', []]
['TEST', '0:1', ['Ethernet1, Vlan100,', 'Vlan101, Vlan102,', 'Vlan103, Vlan104']]
['TEST2', '1234:4321', []]
```

This was what I was talking about: `'Ethernet1, Vlan100,'`

Proposed
```
FSM Table:
['Name', 'Route_Distinguisher', 'Interfaces']
['MGMT', '0:0', ['Vlan2', 'Vlan3', 'Vlan4']]
['NON', '<not set>', []]
['TEST', '0:1', ['Ethernet1', 'Vlan100', 'Vlan101', 'Vlan102', 'Vlan103', ' Vlan104']]
['TEST2', '1234:4321', []]
```

**Comment by bewing** [comment]
Ah!  I see, I was lazy, and just stripped the commas out later in python.  Might want to update the code to remove the cruft at this point

**Comment by bewing** [comment]
OK, if I read this correctly, when processing lines that might contain interfaces, we process them three times  ( via -> Continue), possibly recording a different interface name to the list each time.  Is there ever a possibility of more than 3 interfaces being on one line?  Can one somehow set a longer line length in the terminal to cause the width of the output to change?   I had started down this path, but then switched and grabbed whole lines, and processed the list later in Python because of this.

**Comment by itdependsnetworks** [comment]
I would add an additional one/two more to buffer, presuming we went down this path. Not too hard to do, just cp line and extend.

Your point remains though, what is the preferred method? Keep it in python or update textfsm?

**Comment by mirceaulinic** [comment]
What's the status here @itdependsnetworks @bewing?

**Comment by bewing** [comment]
After playing with this a little more today, I can't make more than 3 interfaces occur on a line, even with modifying the terminal width of my session.  Since his approach makes for a cleaner TextFSM template, I'm inclined to use his approach and include the template in NTC.

**Review by mirceaulinic — APPROVED** [review]

**Pull request merged**
