### PR TITLE
Fixes #16

### LINKED ISSUE #16: Loopback interfaces missing in get_facts()
The show interfaces status command used to populate the interfaces list in get_facts() does not return any loopback interfaces. Is this intentional? Nothing in the docs/mailing list that I found that states they should be excluded.

### PR DESCRIPTION
**Pull request by dbarrosop**

### CODE REVIEW

**Comment by mirceaulinic** [comment]
@dbarrosop With this do you intend to fix #17 too? The code seems to contain also the changes proposed in #18

**Comment by dbarrosop** [comment]
God dammit! Good catch. I am just tired today and forgot to change the branch.

Will fix it.

**Comment by dbarrosop** [comment]
Fixed.

**Comment by mirceaulinic** [comment]
Is there a button to approve the PR? :)

**Comment by dbarrosop** [comment]
you can use your favorite emoji/gif to show you are happy with it and I will merge and release ;)

**Comment by mirceaulinic** [comment]
🏆

**Comment by mirceaulinic** [comment]
It would be nice to have an "Approve" button though

**Pull request merged**
