### PR TITLE
Allow multiple changes over the same session

### PR DESCRIPTION
**Pull request by mirceaulinic**
Closes https://github.com/napalm-automation/napalm-eos/issues/133

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Ping @bewing - can you test this branch and cross-check that it works as expected?

**Comment by mirceaulinic** [comment]
Before:

```python
>>> i.open()
>>> i.load_merge_candidate(config='ntp server 1.2.3.4')
>>> i.load_merge_candidate(config='ntp server 5.6.7.8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "napalm_eos/eos.py", line 170, in load_merge_candidate
    self._load_config(filename, config, False)
  File "napalm_eos/eos.py", line 127, in _load_config
    raise SessionLockedException('Session is already in use by napalm')
napalm_base.exceptions.SessionLockedException: Session is already in use by napalm
>>>
```

Which is not consistent with other drivers (not sure about IOS).

After:

```python
>>> i.open()
>>> i.load_merge_candidate(config='ntp server 1.2.3.4')
>>> i.load_merge_candidate(config='ntp server 5.6.7.8')
>>> print i.compare_config()
@@ -41,6 +41,8 @@
 ip name-server vrf default 8.8.8.8
 !
 ntp source Loopback0
+ntp server 1.2.3.4
+ntp server 5.6.7.8
```

**Comment by mirceaulinic** [comment]
https://github.com/napalm-automation/napalm-eos/pull/134/commits/1ce1cea06a568cb96168b590be907faa12e91fe5 prevents applying parallel changes within the same configuration session.

**Comment by bewing** [comment]
Can confirm that this resolves saltstack/salt#39149

```shell
root@saltmaster:/srv/salt# salt veos1 state.sls router.ntp
veos1:
----------
          ID: cf_ntp
    Function: netntp.managed
      Result: True
     Comment:
     Started: 06:42:24.061354
    Duration: 5563.203 ms
     Changes:
              ----------
              servers:
                  ----------
                  added:
                      - 192.168.0.1
                  removed:
                      - 10.194.2.17

Summary for veos1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.563 s
```

**Comment by mirceaulinic** [comment]
Thanks for confirmation @bewing!

Anyway, the scope is not to solve that particular case, but more to assure consistency across napalm drivers.

**Comment by dbarrosop** [comment]
Nice!

**Review by dbarrosop — APPROVED** [review]

**Pull request merged**
