### PR TITLE
EOS: Add traceroute()

### PR DESCRIPTION
**Pull request by mirceaulinic**
Body of https://github.com/napalm-automation/napalm-base/pull/10

### CODE REVIEW

**Comment by mirceaulinic** [comment]
To resume: in order to get this merged, I need to wait for https://github.com/napalm-automation/napalm-base/pull/10 and https://github.com/napalm-automation/napalm-eos/pull/5 which depends on https://github.com/napalm-automation/napalm-base/pull/8 which depends on https://github.com/napalm-automation/napalm-base/pull/11. It means that I need to rebase every time and be synchronized with you guys. And this is not OK at all.
My personal opinion: it's too much effort and wasted time for... easing the pull request process? Well, I find it more complicated than before and less friendly. 
We want to grow the community and attract people to implement solutions, but I feel it like we are heading in the opposite direction.

**Comment by dbarrosop** [comment]
I understand your frustration, believe me. But this is mostly due to all the cleaning we are doing. The only requirement you should have for a PR like this one is https://github.com/napalm-automation/napalm-base/pull/10.

I haven't announced the split is ready and I haven't modified anything in the main napalm because I still want to see if this makes sense or not. My gut feeling is that it makes but it's been harder due to some cleaning we have been doing. I am going to try to fix https://github.com/napalm-automation/napalm-base/pull/8 and all the related PRs and then everything should get simpler.

**Comment by mirceaulinic** [comment]
All right, that sounds good :)

**Comment by dbarrosop** [comment]
I guess we should close this one for the time being, right? Otherwise feel free to reopen it.

**Comment by mirceaulinic** [comment]
No, I think it's fine, implements the traceroute method. Base: https://github.com/napalm-automation/napalm-base/pull/17

**Comment by mirceaulinic** [comment]
Just forgot to paste the link, sorry.
Otherwise, feel free to comment for improvements in the output structure etc :)

**Comment by dbarrosop** [comment]
Ok, sorry for closing it. I am travelling and working on a tiny screen with limited connectivity is a bit challenging. Specially when there are like 25 new PRs in two days... ;) At least you were kind enough to split them by functionality, which will keep my sanity intact (although it might lead to carpal tunnel issues)

**Comment by mirceaulinic** [comment]
Yes, I understand, no hurry at all, enjoy your time :-)

Have I exaggerated again? :D

**Comment by dbarrosop** [comment]
I merged `napalm-base` and re-run the test. However, they are still failing, can you check?

**Comment by mirceaulinic** [comment]
@dbarrosop this one is ready too now. As well, because of my copy-paste error, needs https://github.com/napalm-automation/napalm-base/pull/20 merged to get it work properly.

**Comment by dbarrosop** [comment]
The test is still failing, could you check?

**Pull request merged**
