### PR TITLE
WIP: Add _oc_platform private method

### PR DESCRIPTION
**Pull request by bewing**
Define a method to translate eAPI dictionaries into OpenConfig
platform information.

Used by napalm-automation/napalm-yang#38 EOS platform parser.

Still needs unit tests.

And yes, it could probably use 2 more refactoring passes.

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by dbarrosop** [comment]
This is perfect timing! :)

ping @mirceaulinic 

We have been talking about this, looking for the best approach. I think we should try something slightly different. Let's back out for a second and go to `napalm-yang`, the way I would like to do this is:

```
metadata:
    processor: TextParser
    execute:
        - method: cli
          args:
              commands:
                - "show inventory"
                - "show environment temperature"
                - "show interfaces"
                - "show interfaces transceiver"
          process: eos_oc_platform
```

Then the idea is that your code here would instead live in `napalm-yang`. We would probably have some folder where we put "processors" we can use after gathering the data.

The reason for this would be to remove the dependency between `napalm-yang` and the driver as the only thing `napalm-yang` will need is some already existing method to gather data from the device. All the processing code lives with `napalm-yang`. A good side effect is that we keep the tests where they are relevant as the mocking data for `napalm-yang` will still require the output of the show commands instead of the output of the private method.

I think this would satisfy my requirements that we have to use the DSL even when we process the output with python code while satisfying @mirceaulinic concerns regarding flexibility and unnecessary dependencies between repos.

Thoughts?

**Comment by bewing** [comment]
One of my concerns would be code living in napalm-yang that might have to change based on upstream changes in underlying drivers (pyeapi, netmiko, etc) that might alter the output of specific commands -- then instead of saying we need version x.x.x of napalm-eos for a specific EOS release, we now say that we need x.x.x of napalm-yang for a specific EOS release.

**Comment by dbarrosop** [comment]
> might have to change based on upstream changes in underlying drivers (pyeapi, netmiko, etc)

If they make backwards incompatible changes we have bigger problems tbh and if that happens, fixing `napalm-eos` would immediately fix `napalm-yang` as long as we keep our API stable. Also, I don't really expect this to happen as we are using very raw and simple commands (like get_rpc on junos or run_commands on ios/eos). The most likely scenario is that different versions will have different outputs but that's a concern for the profiles anyway.

An interesting side effect of having this as a post_processing filter in `napalm-yang` is that you could still gather the data yourself with netmiko/pyez/pywhatever directly and pass it into the parser. If we have the code in the driver this is no longer true for a subset of the models.

**Comment by dbarrosop** [comment]
The more I think about this the more I think we should use in `napalm-yang` only the `run_commands` and implement this private function as a "post_processing" function in `napalm-yang`. Not only removes the napalm-yang's dependency of a particular `napalm-eos` version with this method but it also allows you to interact with `napalm-yang` sending the "raw" data from the device via the `config/state` parameters and having napalm-yang do all the processing (which will be great for offline processing of configuration/state or to use napalm-yang with netmiko directly without using napalm-ios, for example). @bewing @mirceaulinic thoughts?

**Comment by mirceaulinic** [comment]
Sounds good to me @dbarrosop

**Comment by bewing** [comment]
what he said @dbarrosop @mirceaulinic

**Comment by dbarrosop** [comment]
I am closing this one. We should move this code to `napalm-yang` as discussed to avoid  the dependency loop.

**Pull request closed without merging**
